public class MethNestTry {
    static void nesttry(int a ){
        try {//nested try block
            /*if one command arg is used  than divide by zero exception
            * will be generated by following code.*/
            if(a == 1) a = a / (a-a);//division by zero
            /* If two command args are used, than generate an out of bounds exception. */
            if( a == 2){
                int[] c = {1};
                c[42] = 99; //generate an out of bounds exception
            }
        }catch (ArrayIndexOutOfBoundsException e){
            System.out.println("Array Index out of bounds " + e);
        }
    }

    public static void main(String[] args) {

        try {
            int a = args.length;
            /* If no command args are present, the following statement with generate divide by zero exception
             */
            int b = 42 / a;
            System.out.println("a = " + a);
            nesttry(a);
        }catch (ArithmeticException e){
            System.out.println("Divide by zero: " + e);
        }
    }
}
